### ISSUE TITLE
Enumall error

### ISSUE THREAD

**Issue by Chan9390** [reconned/domained#4]
This error pops-up if you are running the tool on Debian.

```
Running Command: python bin/domain/enumall.py <domain>
Traceback (most recent call last):
  File "bin/domain/enumall.py", line 26, in <module>
    from recon.core import base
ImportError: No module named recon.core
```

**Comment by lianfeng30** [comment]
Mac 和 Windows下不行的
请在kali下安装@Chan9390

**Comment by reconned** [comment]
Thanks lianfeng30! Chan9390, please install the script in Kali Linux / Debian (with Recon-ng installed - required for enumall) environment and then run "python domained --install" - if you have not already. Let me know if that solves the problem.

**Comment by Chan9390** [comment]
So you want me to install recon-ng ?
I would suggest you to add a feature to the tool to check if recon-ng exists on the system. If yes, good to continue else raise an exception/error and then exit

**Comment by reconned** [comment]
@Chan9390, thanks - that is a great idea and I think I will recommend Kali Linux (since these are third party tools and have their own dependencies) 

This afternoon I will make the following changes:
1. Check if user is running Kali Linux and if not warn + recommend Kali Linux
2. Add Recon-ng to the install script (apt-get update && apt-get install recon-ng) or the full path for non-Kali users [Recon-ng](https://bitbucket.org/LaNMaSteR53/recon-ng/wiki/Usage%20Guide)
3. Update Readme.md

**Comment by Chan9390** [comment]
Waiting for the update !

**Comment by reconned** [comment]
Sorry @Chan9390 for the delay - updated. Thanks!
